# Read the Docs configuration file
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  version: 3.7
  system_packages: True
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - backends
